// ---------- dflatpp.h

#ifndef DFLATPP_H
#define DFLATPP_H

#define VERSION "D-Flat++ Version 3"

#include "dfwindow.h"
#include "desktop.h"
#include "applicat.h"
#include "dialog.h"
#include "textbox.h"
#include "label.h"
#include "listbox.h"
#include "editbox.h"
#include "editor.h"
#include "button.h"
#include "pbutton.h"
#include "toolbar.h"
#include "checkbox.h"
#include "radio.h"
#include "popdown.h"
#include "menusel.h"
#include "notice.h"

#endif



